//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSI.StudentManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public string StudentID { get; set; }
        public int AddressID { get; set; }
        public long AddresTypeID { get; set; }
        public string DoorNo { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string Locality { get; set; }
        public long CityID { get; set; }
        public long StateID { get; set; }
        public long PincodeID { get; set; }
    }
}
