//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSI.StudentManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Completion
    {
        public long CompletionID { get; set; }
        public string CourseStatus { get; set; }
        public long CertificationStatusID { get; set; }
        public string FeedbackStatus { get; set; }
        public string PlacementRequired { get; set; }
        public string CertificateName { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public long PlacementID { get; set; }
        public string RegistrationID { get; set; }
    
        public virtual Registration Registration { get; set; }
    }
}
