//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSI.StudentManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUp
    {
        public long FollowUpID { get; set; }
        public string FollowUpType { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public string Comment { get; set; }
        public string FollowUpReferenceID { get; set; }
    }
}
