//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSI.StudentManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public long InvoiceID { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public int AmountPaid { get; set; }
        public Nullable<int> AmountTobePaid { get; set; }
        public string CollectedBy { get; set; }
        public long PaymentStatusID { get; set; }
        public long PaymentModeID { get; set; }
        public string ReceiptNo { get; set; }
        public string ChequeNo { get; set; }
        public string ChequeDrawnFrom { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string ChequeName { get; set; }
        public string RegistrationID { get; set; }
    
        public virtual Registration Registration { get; set; }
    }
}
