//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSI.StudentManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registration()
        {
            this.Completions = new HashSet<Completion>();
            this.Invoices = new HashSet<Invoice>();
        }
    
        public string RegistrationID { get; set; }
        public System.DateTime DateOfJoin { get; set; }
        public Nullable<long> RegistrationStatusID { get; set; }
        public Nullable<int> CourseDuration { get; set; }
        public string Timings { get; set; }
        public string TrainerName { get; set; }
        public Nullable<long> TrackTypeID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string RegisteredBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public long CompletionID { get; set; }
        public string StudentID { get; set; }
        public string EnquiryID { get; set; }
        public long PaymentSchemeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Completion> Completions { get; set; }
        public virtual Enquiry Enquiry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual Student Student { get; set; }
    }
}
